apiVersion: v1
entries:
  cert-manager-webhook-mijnhost:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2025-12-19T18:51:12.279154+01:00"
    description: A Helm chart for a cert-manager webhook for Mijn.host DNS
    digest: f917457c9a1ec3d38e7cfc425bf7c8c4906bc0534d7e90bf2d35540613b733ed
    name: cert-manager-webhook-mijnhost
    urls:
    - cert-manager-webhook-mijnhost-1.0.0.tgz
    version: 1.0.0
generated: "2025-12-19T18:51:12.278868+01:00"
